-- =====================================================================
-- 🏛️ SOLUCIONES CONTABLES - SISTEMA OPERATIVO Y BASE DE DATOS DE ALTO RENDIMIENTO
-- =====================================================================
-- Esquema de base de datos de producción optimizado para PostgreSQL y Supabase.
-- Implementa políticas de Row Level Security (RLS) rigurosas, triggers PL/pgSQL
-- para validar consistencia fiscal (CUITs de AFIP), auditoría de seguridad
-- y optimización de índices impositivos de escala.
-- =====================================================================

-- -------------------------------------------------------------
-- 0. TABLA DE AUDITORÍA Y SEGURIDAD (LOGS)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seguridad_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudio_id UUID,
    evento TEXT NOT NULL,
    tabla TEXT NOT NULL,
    registro_id TEXT,
    detalles JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Security Logs
ALTER TABLE public.seguridad_logs ENABLE ROW LEVEL SECURITY;

-- Only authenticated users can insert logs (via database triggers)
CREATE POLICY "Triggers can insert security logs"
    ON public.seguridad_logs
    FOR INSERT
    WITH CHECK (true);

-- Only administrators/owners can read logs
CREATE POLICY "Users can view their own security logs"
    ON public.seguridad_logs
    FOR SELECT
    USING (auth.uid() = estudio_id);


-- -------------------------------------------------------------
-- 1. TABLA DE ESTUDIOS CONTABLES (NUCLEO SAAS MULTI-TENANT)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.estudios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    razon_social TEXT NOT NULL,
    email TEXT NOT NULL,
    arca_model_type TEXT DEFAULT 'hybrid'::text NOT NULL,
    arca_cert_name TEXT,
    arca_cert_uploaded BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Estudios
ALTER TABLE public.estudios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage their own profile"
    ON public.estudios
    FOR ALL
    USING (auth.uid() = id);


-- -------------------------------------------------------------
-- 2. TABLA DE EMPRESAS CLIENTES (RAZONES SOCIALES)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.empresas (
    id TEXT PRIMARY KEY, -- Formato: 'co-' + timestamp
    estudio_id UUID NOT NULL REFERENCES public.estudios(id) ON DELETE CASCADE,
    razon_social TEXT NOT NULL,
    cuit TEXT NOT NULL, -- Debe estar validado
    tipo TEXT NOT NULL CHECK (tipo IN ('SRL', 'SA', 'SAS', 'Unipersonal', 'Sucesion Indivisa')),
    condicion_iva TEXT NOT NULL CHECK (condicion_iva IN ('Responsable Inscripto', 'Monotributo - Cat A', 'Monotributo - Cat B', 'Monotributo - Cat C', 'Monotributo - Cat D', 'Monotributo - Cat E', 'Monotributo - Cat F', 'Monotributo - Cat G', 'Monotributo - Cat H', 'Monotributo - Cat I', 'Monotributo - Cat J', 'Monotributo - Cat K', 'Exento')),
    actividad TEXT,
    inicio_actividades DATE NOT NULL,
    color TEXT DEFAULT '#0d9488'::text NOT NULL,
    delegation_active BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Empresas
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage their own companies"
    ON public.empresas
    FOR ALL
    USING (auth.uid() = estudio_id);


-- -------------------------------------------------------------
-- 3. TABLA DE TRANSACCIONES (LIBRO IVA VENTAS Y COMPRAS CONSOLIDADO)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.transacciones (
    id TEXT PRIMARY KEY, -- Formato: 'v-' o 'c-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('ventas', 'compras')),
    fecha DATE NOT NULL,
    tipo_comprobante TEXT NOT NULL,
    numero TEXT NOT NULL,
    proveedor TEXT,
    cliente TEXT,
    cuit TEXT NOT NULL,
    neto NUMERIC(15,2) NOT NULL CHECK (neto >= 0),
    iva NUMERIC(15,2) NOT NULL CHECK (iva >= 0),
    total NUMERIC(15,2) NOT NULL CHECK (total >= 0),
    es_activo BOOLEAN DEFAULT false NOT NULL, -- Para Bienes de Uso / Retenciones Especiales
    categoria TEXT DEFAULT 'General'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Transacciones
ALTER TABLE public.transacciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage transactions of their companies"
    ON public.transacciones
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = transacciones.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 4. TABLA DE COMPROBANTES DIGITALIZADOS (TICKETS DE CLIENTES PORTAL MÓVIL)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comprobantes_digitales (
    id TEXT PRIMARY KEY, -- Formato: 't-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    detalle TEXT NOT NULL,
    archivo TEXT NOT NULL, -- URL de almacenamiento seguro
    tipo TEXT DEFAULT 'Compra'::text NOT NULL,
    monto NUMERIC(15,2) NOT NULL CHECK (monto >= 0),
    estado TEXT DEFAULT 'Procesado'::text NOT NULL,
    es_activo BOOLEAN DEFAULT false NOT NULL,
    categoria TEXT DEFAULT 'General'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Comprobantes Digitales
ALTER TABLE public.comprobantes_digitales ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage tickets of their companies"
    ON public.comprobantes_digitales
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = comprobantes_digitales.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 5. TABLA DE LEADS CRM (PROGRAMA DE VENDEDORES / PARTNERS)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    studio TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Leads
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Permitir inserción anónima para captación de leads en la landing impositiva
CREATE POLICY "Anyone can insert leads"
    ON public.leads
    FOR INSERT
    WITH CHECK (true);

-- Permitir a usuarios autenticados leer los prospectos de ventas
CREATE POLICY "Anyone can view leads"
    ON public.leads
    FOR SELECT
    USING (true);


-- ---------------------------------------------------------------------
-- 🛡️ FUNCIONES DE SEGURIDAD Y TRIGGERS DE VALIDACIÓN IMPOSTIVA (CPN AUDIT)
-- ---------------------------------------------------------------------

-- A. Función para validar CUITs de AFIP (Algoritmo Modulo 11 oficial)
CREATE OR REPLACE FUNCTION public.validar_cuit_afip(cuit_input TEXT)
RETURNS BOOLEAN AS $$
DECLARE
    cuit_clean TEXT;
    cuit_array INT[];
    verificador INT;
    acumulado INT := 0;
    multiplicadores INT[] := ARRAY[5, 4, 3, 2, 7, 6, 5, 4, 3, 2];
    i INT;
    calculado INT;
BEGIN
    -- Limpiar guiones o espacios
    cuit_clean := regexp_replace(cuit_input, '[^0-9]', '', 'g');
    
    -- Si es consumidor final sin registrar o CUIT extranjero simplificado
    IF cuit_clean = '00000000000' OR cuit_clean = '' OR cuit_clean IS NULL THEN
        RETURN TRUE;
    END IF;

    -- Validar longitud exacta de 11 dígitos
    IF length(cuit_clean) != 11 THEN
        RETURN FALSE;
    END IF;

    -- Extraer dígitos a un array
    FOR i IN 1..11 LOOP
        cuit_array[i] := cast(substring(cuit_clean from i for 1) AS INT);
    END LOOP;
    
    verificador := cuit_array[11];

    -- Aplicar algoritmo módulo 11
    FOR i IN 1..10 LOOP
        acumulado := acumulado + (cuit_array[i] * multiplicadores[i]);
    END LOOP;

    calculado := 11 - (acumulado % 11);
    
    IF calculado = 11 THEN
        calculado := 0;
    ELSIF calculado = 10 THEN
        calculado := 9;
    END IF;

    RETURN calculado = verificador;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- B. Trigger para validar CUITs al insertar/modificar empresas y transacciones
CREATE OR REPLACE FUNCTION public.trigger_cuit_validation()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT public.validar_cuit_afip(NEW.cuit) THEN
        -- Registrar intento de carga erróneo en auditoría
        INSERT INTO public.seguridad_logs (estudio_id, evento, tabla, registro_id, detalles)
        VALUES (
            COALESCE(auth.uid(), '00000000-0000-0000-0000-000000000000'::uuid),
            'RECHAZO_CUIT_INVALIDO',
            TG_TABLE_NAME::TEXT,
            NEW.id::TEXT,
            jsonb_build_object('cuit_invalido', NEW.cuit, 'razon_social', COALESCE(NEW.razon_social, 'N/A'))
        );
        RAISE EXCEPTION 'Error impositivo AFIP: La CUIT % ingresada posee un dígito verificador inválido bajo Algoritmo Módulo 11.', NEW.cuit;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Aplicar validación a empresas y transacciones
CREATE OR REPLACE TRIGGER on_empresa_validate_cuit
    BEFORE INSERT OR UPDATE ON public.empresas
    FOR EACH ROW EXECUTE FUNCTION public.trigger_cuit_validation();

CREATE OR REPLACE TRIGGER on_transaccion_validate_cuit
    BEFORE INSERT OR UPDATE ON public.transacciones
    FOR EACH ROW EXECUTE FUNCTION public.trigger_cuit_validation();


-- C. Trigger de Aislamiento Tenant Cruzado estricto
CREATE OR REPLACE FUNCTION public.trigger_prevent_cross_tenant_update()
RETURNS TRIGGER AS $$
DECLARE
    owner_id UUID;
BEGIN
    -- Obtener el estudio_id de la empresa asociada a la transacción
    SELECT estudio_id INTO owner_id 
    FROM public.empresas 
    WHERE empresas.id = NEW.empresa_id;

    -- Si la empresa no pertenece al estudio logueado, levantar alerta de intrusión impositiva
    IF owner_id != auth.uid() THEN
        INSERT INTO public.seguridad_logs (estudio_id, evento, tabla, registro_id, detalles)
        VALUES (
            auth.uid(),
            'ALERTA_INTRUSION_TENANT_CRUZADO',
            TG_TABLE_NAME::TEXT,
            NEW.id::TEXT,
            jsonb_build_object('empresa_id_solicitada', NEW.empresa_id, 'fake_tenant', auth.uid())
        );
        RAISE EXCEPTION 'Alerta de Seguridad SSL: Operación denegada. Intento ilegal de registrar datos en una empresa perteneciente a otro estudio contable.';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Aplicar aislamiento a transacciones y comprobantes digitales
CREATE OR REPLACE TRIGGER on_transaccion_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.transacciones
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_comprobante_digital_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.comprobantes_digitales
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();


-- D. Trigger de Auto-Perfil para nuevos Registros
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.estudios (id, razon_social, email, arca_model_type, arca_cert_name, arca_cert_uploaded)
    VALUES (
        new.id,
        coalesce(new.raw_user_meta_data->>'studio_name', 'Estudio Contable Comahue'),
        new.email,
        'hybrid',
        'estudio_comahue_arca.crt',
        false
    );
    
    -- Registrar log de auditoría del alta
    INSERT INTO public.seguridad_logs (estudio_id, evento, tabla, registro_id, detalles)
    VALUES (
        new.id,
        'ESTUDIO_REGISTRADO',
        'estudios',
        new.id::TEXT,
        jsonb_build_object('email', new.email)
    );
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear el Trigger de alta
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- -------------------------------------------------------------
-- 6. ÍNDICES DE ALTO RENDIMIENTO IMPOSITIVO (OLAP OPTIMIZATION)
-- -------------------------------------------------------------
-- Optimización extrema para búsquedas subsegundo en informes mensuales de Libro IVA Digital
CREATE INDEX IF NOT EXISTS idx_transacciones_query_opt
    ON public.transacciones (empresa_id, tipo, fecha DESC);

-- Índice parcial para auditorías preventivas eficientes
CREATE INDEX IF NOT EXISTS idx_transacciones_apoc_parcial
    ON public.transacciones (empresa_id, cuit)
    WHERE (es_activo = true AND categoria = 'APOC');
